name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    
    name: Tests with PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.3, 7.4]
    services:
      postgres: 
        image: postgres:alpine
        ports: 
          - 5432:5432
        env:
          POSTGRES_PASSWORD: secret

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: none

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      
      - name: Clear config
        run: php artisan config:clear
        
      - name: Running tests
        run: vendor/bin/phpunit --verbose
    
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name != 'pull_request'
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login to Heroku Container registry
        run: heroku container:login
      
      - name: Build and push
        run: heroku container:push -a ${{ github.event.repository.name }} web

      - name: Release
        run: heroku container:release -a ${{ github.event.repository.name }} web
